### ISSUE TITLE
Libsass Revisited

### ISSUE THREAD

**Issue by 58bits** [at-import/Singularity#215]
I'm thinking of moving to Libsass via https://github.com/sass/node-sass, and https://github.com/sindresorhus/grunt-sass 

It's not totally clear to me that libsass is now parity with Sass 3.3 - although with Libsass 3.2 I don't see any issues here at http://sass-compatibility.github.io/

Does it look like Singularity will now work with the latest version of Libsass?

**Comment by 58bits** [comment]
Well it worked. It was simply...

`npm install --save-dev grunt-sass`

... which loaded the node-sass dependency, and then swap from...

`grunt.loadNpmTasks('grunt-contrib-sass');`

...to

`grunt.loadNpmTasks('grunt-sass');`

My current sass:dev and sass:dist tasks all worked fine (except for sass-globbing which wasn't a big deal to remove).

**Comment by 58bits** [comment]
For interest, here's my sass task definition. There are fewer options than `grunt-contrib-sass`. `cwd`,  `expand`, and `ext` all come from the grunt api.

```
    /**
     * Sass
     */
    sass: {
      dev: {
        options: {
          outputStyle: 'expanded',
          sourceMap: true
        },
        files: [{
          expand: true,
          cwd: 'assets/scss',
          src: ['*.scss'],
          dest: 'public/css/',
          ext: '.css'
        }]
      },
      dist: {
        options: {
          outputStyle: 'compressed',
          sourceMap: false
        },
        files: [{
          expand: true,
          cwd: 'assets/scss',
          src: ['*.scss'],
          dest: 'public/css/',
          ext: '.css'
        }]
      }
    },
```

**Comment by 58bits** [comment]
Ouch - all was well until I set `@include sgs-change('debug', true);` - after which the grunt task to process the stylesheets, exited with `Bus error: 10`

Any ideas?

**Comment by digitaldonkey** [comment]
Is there a chance that singularity will be updated to fully work with lib-sass?

**Comment by 58bits** [comment]
At the time I tried, it worked fine, until I enabled debug mode. Until the W3C CSS Grid module comes along I was/am planning on using Singularity. Having used many grid systems, I think it's the best. Very clean, very comprehensive. It would be great if the authors could take a quick look at this, to see if there are any obvious stumbling blocks to making Singularity Libsass compatible.

**Comment by Vagelis-Prokopiou** [comment]
I use singularity (and extras) with gulp-sass (libsass) with no problem whatsoever.

**Comment by 58bits** [comment]
@Vaggos in debug mode as well?

**Comment by digitaldonkey** [comment]
For me it works but not background-grid(requiering debug mode).

**Comment by 58bits** [comment]
@digitaldonkey yes - that's the same problem I was having.

**Comment by Vagelis-Prokopiou** [comment]
Yes. In the past I had  problems if I declared a grid with more than 12
columns with debug mode on (I think this has been solved anyway). But now,
I never use more than 12 columns. In fact, I use asymmetric grids. The only
"problem" I have encountered is that sometimes my elements don't align
perfectly with the background-grid. But that is normal from what I have
read.

**Comment by dvangimst** [comment]
I have the same error when I turn on the debug mode. The strange thing is, that I just tried this on Sassmeister, and it works! Although I can't figure out what the difference is between my local environment (gulp-sass) and Sassmeister. Probably are the version slightly different.

**Comment by Snugug** [comment]
With the exception of the debug grid in certain grid configurations on certain machines, Singularity is 100% Libsass compatible and has been since roughly April (possibly earlier, but 3.2 was a _big_ compatibility release for Libsass). Be sure you're using the most up-to-date version of Libsass.

The reason for this is due to heavy string manipulation to create an SVG for the background image; something that's more accurate than a background gradient, and in certain configurations on certain machines this crashes. For those using [Eyeglass](https://github.com/sass-eyeglass/eyeglass) there has been consideration of moving the string code out of Sass and in to JavaScript although it hasn't happened yet (and that would be a separate issue)

**Comment by 58bits** [comment]
I've just updated to the latest versions of grunt-sass, and libsass, and I still receive `Bus error: 10` when compiling style sheets with libsass.

As far as I can tell, my configuration is pretty standard.

```
@import "../bower_components/breakpoint-sass/stylesheets/breakpoint";
@import "../bower_components/sass-toolkit/stylesheets/toolkit";
@import "../bower_components/singularity/stylesheets/singularitygs";

@include sgs-change('debug', true);
@include sgs-change('mobile first', true);
@include sgs-change('output', 'isolation');

$smallest: 500px;
$smaller: 600px;
$small: 700px;
$medium: 900px;
$large: 1200px;
$verylarge: 1500px;

@include add-grid(4);
@include add-grid(8 at $small);
@include add-grid(14 at $medium);
@include add-grid(16 at $large);
@include add-gutter(0);
@include add-gutter(0 at $small);
@include add-gutter(0 at $medium);
@include add-gutter(0 at $large);
```

I can live with switching back to Ruby sass if I need to debug a layout, and using Libsass for regular workflow, and I truly appreciate the contributions the authors of Singularity have made. But are you sure this issue is closed?

**Comment by Snugug** [comment]
Can you recreate that error in Sassmeister? What about with just node sass?

**Comment by Snugug** [comment]
In fact, http://sassmeister.com/gist/5f275d1d93a839b4b960

**Comment by 58bits** [comment]
Yup - it works on SassMeister - including my updated gist, with a container and background grid color set... http://sassmeister.com/gist/ac31969a3b5dfcbef1a5

But calling this from the node-sass cli ...

`node-sass --output-style expanded ./scss/main.scss  ../public/css/main.css`

.. and I still see `Bus error: 10`

:-(

**Comment by 58bits** [comment]
Set `@include sgs-change('debug', false);`

And...

```
node-sass --output-style expanded ./scss/main.scss  ../public/css/main.css
Rendering Complete, saving .css file...
```

**Comment by Snugug** [comment]
Please provide the full error and the smallest set of code needed to recreate this error. As well as your OS

**Comment by 58bits** [comment]
A similar report here... https://github.com/at-import/Singularity/issues/211

Here's the minimum scss file needed to generate the error (the same as Sassmeister)

``` scss
@import "../bower_components/breakpoint-sass/stylesheets/breakpoint";
@import "../bower_components/sass-toolkit/stylesheets/toolkit";
@import "../bower_components/singularity/stylesheets/singularitygs";

@include sgs-change('debug', true);
@include sgs-change('mobile first', true);
@include sgs-change('output', 'isolation');

$smallest: 500px;
$smaller: 600px;
$small: 700px;
$medium: 900px;
$large: 1200px;
$verylarge: 1500px;

@include add-grid(4);
@include add-grid(8 at $small);
@include add-grid(14 at $medium);
@include add-grid(16 at $large);
@include add-gutter(0);
@include add-gutter(0 at $small);
@include add-gutter(0 at $medium);
@include add-gutter(0 at $large);


.container {
  height: 100vh;
  position: relative;
  width: 100%;
  margin: 0 auto;
  @include background-grid($color: #338);
}
```

Here's the command...

`node-sass --output-style expanded ./scss/test.scss  ./scss/test.css`

And error...

`Bus error: 10`

```
node-sass --version
node-sass   3.4.2   (Wrapper)   [JavaScript]
libsass     3.3.2   (Sass Compiler) [C/C++]
```

OS X El Capitan Version 10.11.1 (15B42)
Node v5.1.0

I don't see any debug or verbose output options for https://github.com/sass/node-sass

**Comment by Snugug** [comment]
Remove the background grid mixin. That's the thing that's known to give people issue with Libsass and the subject of my comment closing this thread.

**Comment by 58bits** [comment]
Yes - I know it's the  `@include background-grid($color: #338);` that causes the failure when `'debug', true` - and that's the reason I opened the issue (although not the original title). It's the `background-grid` that I was hoping to see/use in debug mode.

Any ideas at all why it works here... http://sassmeister.com/gist/ac31969a3b5dfcbef1a5 and not on my local build?

**Comment by 58bits** [comment]
I moved node-sass to global `npm install -g node-sass` and tried again...

```
node-sass scss/test.scss scss/test.css
Illegal instruction: 4
```

The error message has changed. It looks like a problem with the way libsass is being compiled under mac os x.

http://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

I'll continued to investigate...

@Snugug  - are you on Mac OS X or Linux?

**Comment by Snugug** [comment]
OSX.

This is a problem with how Libsass is compiled, not a compatibility issue with Singularity. The error is something that doesn't affect everyone and doesn't affect everyone the same way when it does except for the background grid call. I'd file an issue with Libsass as its the thing that's failing, not Singularity.

**Comment by 58bits** [comment]
Yup - agreed.

I've also just compiled the https://github.com/sass/sassc cli, and used this to compile my main stylesheet, in debug mode, and with `@include background-grid($color: #338);` and everything works fine. The stylesheet is compiled perfectly and the background-grid is displayed.

So it looks like the problem might actually be with https://github.com/sass/node-sass

I'll submit an issue there and see how it goes...

**Comment by 58bits** [comment]
For interest... this works...

``` scss
@import "../bower_components/breakpoint-sass/stylesheets/breakpoint";
@import "../bower_components/sass-toolkit/stylesheets/toolkit";
@import "../bower_components/singularity/stylesheets/singularitygs";

@include sgs-change('debug', true);
@include sgs-change('mobile first', true);
@include sgs-change('output', 'isolation');

$smallest: 500px;
$smaller: 600px;
$small: 700px;
$medium: 900px;
$large: 1200px;
$verylarge: 1500px;

@include add-grid(4);
@include add-grid(6 at $small);
@include add-gutter(0);
@include add-gutter(0 at $small);

.container {
  height: 100vh;
  position: relative;
  width: 100%;
  margin: 0 auto;
  @include background-grid($color: #338);
}
```

However, as soon as I create a grid that is more than 8 columns, or greater, then node-sass fails.

It appears to be having a problem with the large embedded svg strings.

**Comment by 58bits** [comment]
If the inline svg string is less than about 1,558 bytes - node-sass compiles fine.

If the inline svg string is about 1,673 bytes or greater - the error is generated.

It doesn't matter how many inline svg strings there are - as long as no single inline svg embed goes over roughly 1,558 bytes.

**Comment by saper** [comment]
This is a stack overflow. Some structures passed on the stack are too large and probably there are also some loops in the processing. This issue is in part a bug in libsass (excessive memory use in some cases) - this may break `sassc` standalone compiler at times as well. But this is also a limitation of node (and thus node-sass), because [the default stack size is more limited on OSX ](https://developer.apple.com/library/mac/qa/qa1419/_index.htm). We are still investigating this issue.

**Comment by saper** [comment]
On a side note @snugug do you have any reference the discussion about string handling in eyeglass? One of the proposals at https://github.com/sass/node-sass/issues/1088 is to allow easier exchange of strings between libsass and the JavaScript code.

**Comment by Snugug** [comment]
Eyeglass is still settling down, especially in Gulp land where I see the majority of use, so nothing yet.

**Comment by saper** [comment]
That's okay - we need to sort it out ASAP, _before_ eyeglass settles down.

**Comment by saper** [comment]
Is this correct way to invoke singularity without using grunt?

https://github.com/saper/singularity-project-bug-1289

it seems to me when trying to use eyeglass (https://github.com/saper/singularity-project-bug-1289/blob/a71c26f85ad4d58f409345812af90fc17ea72bbd/index.js) it tries to eat the module's directory as input:

```
> node index.js 
{ file: 'source/6c5443acf20fe855f854.scss',
  includePaths: 
   [ '/home/saper/sw/problems/node-sass/1289/singularity-project-bug-1289/node_modules/singularitygs/stylesheets',
     '/home/saper/sw/problems/node-sass/1289/singularity-project-bug-1289/node_modules/breakpoint-sass/stylesheets',
     '/home/saper/sw/problems/node-sass/1289/singularity-project-bug-1289/node_modules/sass-toolkit/stylesheets' ] }
The following modules did not declare an eyeglass version:
  breakpoint
  toolkit
  singularitygs
Please add the following to the module's package.json:
  "eyeglass": { "needs": "^0.8.0" }
{ [Error: Invalid CSS after "": expected 1 selector or at-rule, was "?��"]
  formatted: 'Error: Invalid CSS after "": expected 1 selector or at-rule, was "?��"\n        on line 1 of node_modules/breakpoint-sass/stylesheets\n>> ?��\n   ^\n',
  message: 'Invalid CSS after "": expected 1 selector or at-rule, was "?��"',
  column: 1,
  line: 1,
  file: '/home/saper/sw/problems/node-sass/1289/singularity-project-bug-1289/node_modules/breakpoint-sass/stylesheets',
  status: 1 } null
```

**Comment by saper** [comment]
So we have opened https://github.com/sass/libsass/issues/1823 and the conclusion so far is that such a recursive implementation of str-replace will sooner or later (depending on a string length) lead to stack overflow. @mgreter posted a suggestion how to re-write the function using iteration, which does not abuse the stack.

**Comment by 58bits** [comment]
Hi @saper and Happy New Year! Thank's a ton for the time and effort you and @xzyfer have put into chasing this one down. Also thanks to @mgreter for the coding suggestion. If this works, and it makes it into Singularity - well then that would be awesome. @Snugug - let me know if there's anything else I can do to help. Hope everyone's 2016 is off to a great start, and that you all have a happy, healthy, and prosperous 2016!

**Comment by Vagelis-Prokopiou** [comment]
I agree with @58bits 100%. I wish I also could help in some way.

**Comment by saper** [comment]
According to https://gist.github.com/HugoGiraudel/1b4f2da5527830088e4d @HugoGiraudel and @valeriangalliat worked on this `str-replace` implementation before

**Comment by 58bits** [comment]
So it looks like this has gone all the way to libuv :-) https://github.com/libuv/libuv/pull/671

**Comment by saper** [comment]
Well, but I'd recommend reopening this bug and fixing the problem in the `str-replace` function anyway. For some string length this function **will** overflow the stack.

**Comment by xzyfer** [comment]
I agree with @saper. At some point this will potentially overflow even Ruby Sass.

**Comment by Snugug** [comment]
Overflow ALL THE THINGS!

A simple fix is, as there are a limited number of characters I actually need to replace, a PR could be made to simply have those be written directly and bypass the whole need for str-replace.  If someone would like to do that I'd be all in favor.

**Comment by mgreter** [comment]
Please check https://github.com/sass/libsass/issues/1823#issuecomment-168464078 for a proper solution for str-replace without recursion. This would be the proper fix (if the presented function is really equivalent to the old recursive implementation). Basically means we need a few people to actually test it and confirm that it works correctly.
BTW. the pivotal is not really the length of the string, it's the number of replacements in the string.
