### ISSUE TITLE
Rounding errors

### ISSUE THREAD

**Issue by xonic** [at-import/Singularity#40]
There seem to be rounding errors.

I have a 5 column grid with 188px each column and 10px gutter width, which sums up to 188 \* 5 = 940px + 40px gutters = 980px.
Singularity calculates the gutters like so: 10px, 11px, 11px, 13px and the columns are all only 187px wide.

here is the scss file

``` sass

@import "compass/reset";
@import "compass";
@import "singularitygs";


$columns:   188px 188px 188px 188px 188px;
$gutter:    10px;
$color:     #888;
$padding:   20px;

@include grid-objects(a, $columns, $gutter, $padding, $selector:".");

.wrapper
{
    max-width:980px;
    height:100%;
    margin:0 auto;
    background:green;
}

.foo 
{
    background:$color;
    padding-top:$padding;
    padding-bottom:$padding;
}
```

and the html code

``` html
<html>
    <head>
        <title>Grid test page</title>
        <link href="stylesheets/screen.css" rel="stylesheet">
    </head>
    <body>
        <section class="wrapper">
            <section class="foo a0-1">
                bla
            </section>
            <section class="foo a1-2">
                bla
            </section>
            <section class="foo a2-3">
                bla
            </section>
            <section class="foo a3-4">
                bla
            </section>
            <section class="foo a4-5">
                bla
            </section>
        </section>
    </body>
</html>
```

**Comment by scottkellum** [comment]
@Snugug looks like we didn’t mix new stuff in with building grid objects. I am finishing the output API quick so that can be plugged into this mixin.

**Comment by Snugug** [comment]
What version of Singularity are you using?

Plugging this into Singularity 0.0.11 and checking in Chrome and Firefox, I get that each section is 188px wide, the total width is 180px, the first margin between Column 1 and Column 2 is 9.9833px (which rounds up to 10px in actual browser calculations) and the margin between the rest is exactly 10px. I also get that the total width of your wrapper is 980px.

I've got a feeling that you're not using the latest Singularity after we fixed the large rounding errors we previously had. To check your version of Singularity, run `gem list singularitygs` and look for the largest number. If you aren't using 0.0.11, you aren't using the latest and greatest. If you're using RVM, make sure that that is set for you to use 0.0.11. If you see that you aren't using the latest, run `gem install singularitygs` to update just Singularity or `gem update` to update all of your gems to the latest versions.

**Comment by xonic** [comment]
Well, I think I'm definitely on the newest version, since i installed the gems only yesterday.

Here's some info:

``` code
$ gem list singularitygs

*** LOCAL GEMS ***

singularitygs (0.0.11)


$ gem list compass

*** LOCAL GEMS ***

compass (0.12.2)
```

and I do have rvm installed for managing ruby versions but that's it.

``` code
$ rvm list

rvm rubies

=* ruby-1.9.3-p125 [ x86_64 ]
```

I did use Safari 6. Now I tried Firefox & Chrome which both give more accurate but still not perfect results:

``` code
|    187px    | 10px |   188px    | 10px |    188px    | 10px |    188px    | 11px |    188px    |
```

**Comment by Snugug** [comment]
I can confirm that I see the following in Safari.

```
|    187px    | 10px |   187px    | 11px |    187px    | 11px |    187px    | 13px |    187px    |
```

I can give you a little bit of insight into the issue you're seeing. First and foremost, the larger final margin is actually an attempt by us to reduce any rounding issues you see; it's floated in the opposite direction. If we weren't to float this to the right in this case, you would have seen an 11px margin with 2px left over on the right hand side.

Secondly, this problem isn't actually with Singularity, but rather with the browsers themselves. As [John Albin points out](http://www.palantir.net/blog/responsive-design-s-dirty-little-secret) browsers really _really_ suck at rounding. Fortunately, the method that he describes in his post to do as much as possible to eliminate those rounding errors is precisely what we use in Singularity. Even more than that, Chrome has implemented the same percent rounding solution that's in Firefox, which is why we get really nice results in both. Safari still sucks at rounding, and since the default output for Singularity is, at the moment, percentage based, this is simply a reality of the web and there is nothing we can do about it for the percentage based output. The more important thing, especially when talking about grid systems in general, is that each column lines up with itself and multiple span columns line up with stacked columns above it, and Singularity along with John's method ensures this does, indeed, happen.

Now, I know that's not going to be a satisfactory answer for you as you want a pixel perfect grid. Unfortunately, there is no percentage based grid system out there that will be able to build a pixel perfect grid for you for precisely the same reasons it's not working in Singularity; browsers suck at rounding. That being said, the linked issue that Scott talked about is going to be a way for users to choose their output method, and for you I think you'd want a pixel based output method instead of a percentage based one. I'm going to be spending some time today and tomorrow cranking on what Scott's produced to try and get it to a state we can publish so you can use it.

**Comment by xonic** [comment]
First of all, thanks for the great support.

However, this is a quite satisfactory answer indeed. Of course I was in search for a pixel perfect grid but my main concern is to have a solid, robust and scalable responsive (read fluid) grid. So, yes, it is disappointing that the solution won't be perfect any time soon, but since this is beyond our power, I have no problem dealing with it.

**Comment by Snugug** [comment]
Awesome. I'm glad I was able to explain it then. Happy coding!
